language: node_js
node_js:
  - "stable"
cache: yarn
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  local_dir: build
  target_branch: master
  on:
    branch: development
